version: "3"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "80:5001"
    entrypoint: /app/entrypoint.sh
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-southeast-2
        awslogs-group: nzbills-lg
        awslogs-create-group: "true"
