version: "3"

services:
#  dynamodb-local:
#    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
#    image: "amazon/dynamodb-local:latest"
#    container_name: dynamodb-local
#    ports:
#      - "8000:8000"
#    volumes:
#      - "./docker/dynamodb:/home/dynamodblocal/data"
#    working_dir: /home/dynamodblocal

  app:
#    depends_on:
#      - dynamodb-local
    build: .
    volumes:
      - .:/app
    #    env_file:
    #      - .env
    ports:
      #      - "5000:5000"
      - "80:5001"
    entrypoint: /app/entrypoint.sh
